In [10]:
%pip install -r tic-tac-toe/requirements.txt
%pip install -e tic-tac-toe/

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------------- -------------------------- 3.7/11.0 MB 21.8 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/11.0 MB 21.5 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 18.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.
Obtaining file:///C:/Users/Spencer/Documents/CUBoulder/CSCI7000/Assignment1/tic-tac-toe
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
  Building editable for tictactoe (pyproject.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from tictactoe.board import Board

# Tasks
- Create Data
    - Create Recursive function to get all board positions
    - Create Function to get best move
- Create Transformer
- Train Transformer
- Write article

In [23]:
size = 3
boards = {}
def generate_data(board):
    b = Board()
    if np.array2string(board.flatten()) not in list(boards.keys()):
        boards[np.array2string(board.flatten())] = b.get_best_moves(board)

    for i, j in list(zip(*np.where(board==0))):
        nb = Board()
        nb.set_board(np.copy(board))
        nb.place(i,j)
        new_board = nb.board
        try:
            generate_data(new_board)
        except:
            print(f"i: {i} j: {j} board:{new_board}")
            raise
generate_data(np.array([[0,0,0],
                        [0,0,0],
                        [0,0,0]]))

i: 2 j: 0 board:[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]]
i: 1 j: 2 board:[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]]
i: 1 j: 1 board:[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]]
i: 1 j: 0 board:[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]]
i: 0 j: 2 board:[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]]
i: 0 j: 1 board:[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]]
i: 0 j: 0 board:[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]]


ValueError: Board Position [2, 2] is not empty

In [13]:
arr = np.array([[0,0,0],
          [0,0,0],
          [0,0,0]])

In [15]:
for i in list(np.where(arr == 0)):
    print(i)

[0 0 0 1 1 1 2 2 2]
[0 1 2 0 1 2 0 1 2]


[(np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1)),
 (np.int64(0), np.int64(2)),
 (np.int64(1), np.int64(0)),
 (np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2)),
 (np.int64(2), np.int64(0)),
 (np.int64(2), np.int64(1)),
 (np.int64(2), np.int64(2))]

In [11]:
np.array2string(arr.flatten())

'[0 0 0 0 0 0 0 0 0]'

In [13]:
def num_to_cords(num: int):
    return num // 3, num % 3

